services:
  - type: web
    name: celticstech-api
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/celticstech-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17